<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Thu Jul 14 2022 02:21:10 GMT+0700 (Indochina Time)). */
return array(
	'mobx' => '4.15.4',
	'react' => '16.13.1',
	'react-dom' => '16.13.1'
);
